# Usando Python 3 como imagem base
FROM python:3

# Copiando o arquivo script.py pro container
COPY script.py /

# Setando o diretório
WORKDIR /

# Rodando o script quando o container iniciar
CMD ["python", "script.py"]